# Generated by Django 5.0.6 on 2024-06-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='lable',
            new_name='label',
        ),
    ]
